// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBB_SE_2026_923_2.Data;

#nullable disable

namespace UBB_SE_2026_923_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504193035_skibididopdopdopdyesyes")]
    partial class Skibididopdopdopdyesyes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ERRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedDoctorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDoctorId");

                    b.ToTable("ERRequests", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Hangout", b =>
                {
                    b.Property<int>("HangoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HangoutID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("HangoutID");

                    b.ToTable("Hangouts", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.HangoutParticipant", b =>
                {
                    b.Property<int>("HangoutId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("HangoutId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("HangoutParticipants", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.HighRiskMedicine", b =>
                {
                    b.Property<string>("MedicineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WarningMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MedicineName");

                    b.ToTable("HighRiskMedicines", (string)null);

                    b.HasData(
                        new
                        {
                            MedicineName = "Warfarin",
                            WarningMessage = "Anticoagulant - check INR before prescribing."
                        },
                        new
                        {
                            MedicineName = "Methotrexate",
                            WarningMessage = "Hepatotoxic - confirm dosing and weekly schedule."
                        });
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<float>("DiscountPercentage")
                        .HasColumnType("real");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfPills")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ItemBatch", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfPacks")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "ExpirationDate");

                    b.ToTable("ItemBatches", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ItemSubstance", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("SubstanceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("Concentration")
                        .HasColumnType("real");

                    b.HasKey("ItemId", "SubstanceName");

                    b.HasIndex("SubstanceName");

                    b.ToTable("ItemSubstances", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.MedicalEvaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationsList")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("EvaluationID");

                    b.HasIndex("DoctorId");

                    b.ToTable("MedicalEvaluations", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionButtonText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RecipientStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientStaffId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PickUpDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderQuantity")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("OrderId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.PeriodNote", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("NoteId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("NoteBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("UserId", "NoteId");

                    b.ToTable("PeriodNotes", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.PharmacyHandover", b =>
                {
                    b.Property<int>("PharmacistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HandoverDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PharmacistId", "HandoverDate");

                    b.ToTable("PharmacyHandovers", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ShiftSwapRequest", b =>
                {
                    b.Property<int>("SwapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwapId"));

                    b.Property<int>("ColleagueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SwapId");

                    b.HasIndex("ColleagueId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftSwapRequests", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] <> ''");

                    b.ToTable("Staff", (string)null);

                    b.HasDiscriminator<string>("Role").HasValue("Staff");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Substance", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<float>("LethalDose")
                        .HasColumnType("real");

                    b.HasKey("Name");

                    b.ToTable("Substances", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "Ibuprofen",
                            Description = "Anti-inflammatory pain reliever",
                            LethalDose = 3200f
                        },
                        new
                        {
                            Name = "Paracetamol",
                            Description = "Pain reliever and fever reducer",
                            LethalDose = 4000f
                        },
                        new
                        {
                            Name = "Magnesium",
                            Description = "Mineral supplement for muscle and nerve support",
                            LethalDose = 2500f
                        },
                        new
                        {
                            Name = "Vitamin C",
                            Description = "Vitamin supplement for immune support",
                            LethalDose = 2000f
                        },
                        new
                        {
                            Name = "Cetirizine",
                            Description = "Antihistamine for allergy relief",
                            LethalDose = 500f
                        });
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CycleDays")
                        .HasColumnType("int");

                    b.Property<bool>("DiscountNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("PeriodLasts")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PremenstrualSyndromeOption")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Client");

                    b.Property<DateOnly>("StartPeriodDate")
                        .HasColumnType("date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.UserDiscount", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<float>("DiscountPercentage")
                        .HasColumnType("real");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserDiscounts", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.UserNotification", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStockAlert")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Doctor", b =>
                {
                    b.HasBaseType("UBB_SE_2026_923_2.Models.Staff");

                    b.Property<string>("DoctorStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Pharmacyst", b =>
                {
                    b.HasBaseType("UBB_SE_2026_923_2.Models.Staff");

                    b.HasDiscriminator().HasValue("Pharmacist");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Appointment", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ERRequest", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Doctor", "AssignedDoctor")
                        .WithMany()
                        .HasForeignKey("AssignedDoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedDoctor");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.HangoutParticipant", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Hangout", "Hangout")
                        .WithMany("HangoutParticipantEntries")
                        .HasForeignKey("HangoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Staff")
                        .WithMany("HangoutParticipantEntries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hangout");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ItemBatch", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Item", "Item")
                        .WithMany("ItemBatchEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ItemSubstance", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Item", "Item")
                        .WithMany("ItemSubstanceEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.Substance", "Substance")
                        .WithMany("ItemSubstanceEntries")
                        .HasForeignKey("SubstanceName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Substance");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.MedicalEvaluation", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Doctor", "Evaluator")
                        .WithMany("MedicalEvaluations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Notification", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Order", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.User", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.OrderItem", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.Order", "Order")
                        .WithMany("OrderItemEntries")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.PeriodNote", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.User", "User")
                        .WithMany("PeriodNoteEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.PharmacyHandover", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Pharmacist")
                        .WithMany()
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Shift", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Staff")
                        .WithMany("Shifts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.ShiftSwapRequest", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Colleague")
                        .WithMany("ShiftSwapRequestsAsColleague")
                        .HasForeignKey("ColleagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.Staff", "Requester")
                        .WithMany("ShiftSwapRequestsAsRequester")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colleague");

                    b.Navigation("Requester");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.UserDiscount", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.User", "User")
                        .WithMany("UserDiscountEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.UserNotification", b =>
                {
                    b.HasOne("UBB_SE_2026_923_2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UBB_SE_2026_923_2.Models.User", "User")
                        .WithMany("UserNotificationEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Hangout", b =>
                {
                    b.Navigation("HangoutParticipantEntries");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Item", b =>
                {
                    b.Navigation("ItemBatchEntries");

                    b.Navigation("ItemSubstanceEntries");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Order", b =>
                {
                    b.Navigation("OrderItemEntries");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Staff", b =>
                {
                    b.Navigation("HangoutParticipantEntries");

                    b.Navigation("Notifications");

                    b.Navigation("ShiftSwapRequestsAsColleague");

                    b.Navigation("ShiftSwapRequestsAsRequester");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Substance", b =>
                {
                    b.Navigation("ItemSubstanceEntries");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PeriodNoteEntries");

                    b.Navigation("UserDiscountEntries");

                    b.Navigation("UserNotificationEntries");
                });

            modelBuilder.Entity("UBB_SE_2026_923_2.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalEvaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
