<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Data\Hospital.Data.csproj" />
    <ProjectReference Include="..\Hospital.Services\Hospital.Services.csproj" />
    <ProjectReference Include="..\Hospital.Shared\Hospital.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\ShiftManagement\*.cshtml" />
    <Compile Remove="Controllers\*.cs" />
    <Compile Include="Controllers\AdminController.cs" />
    <Compile Include="Controllers\AuthController.cs" />
    <Compile Include="Controllers\BloodCompatibilityController.cs" />
    <Compile Include="Controllers\GhostController.cs" />
    <Compile Include="Controllers\HomeController.cs" />
    <Compile Include="Controllers\ModulesController.cs" />
    <Compile Include="Controllers\PatientController.cs" />
    <Compile Include="Controllers\PharmacyController.cs" />
  </ItemGroup>

</Project>
